annotations:
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/os: linux
  catalog.rancher.io/certified: rancher
  catalog.rancher.io/namespace: cattle-monitoring-system
  catalog.rancher.io/release-name: rancher-pushprox
apiVersion: v1
appVersion: v9.9.9
description: Sets up a deployment of the PushProx proxy and a DaemonSet of PushProx
  clients.
kubeVersion: '>=1.26.0-0'
name: rancher-pushprox
type: application
version: 9.9.9
